### ISSUE TITLE
如何添加百度云统计？

### ISSUE THREAD

**Issue by stuhua** [zhenchentl/zhenchentl.github.com#1]
请问一下，为什么我一添加百度云统计就有错？？？

**Comment by zhenchentl** [comment]
请问是什么错误？你是怎么添加的

**Comment by stuhua** [comment]
@zhenchentl 
 我是根据这个？我看楼主的没有添加百度云统计。

![qq 20150827150353](https://cloud.githubusercontent.com/assets/5968293/9514485/ea401984-4ccc-11e5-8d22-a13f2bc65dbb.png)

**Comment by zhenchentl** [comment]
我没这么做，你是从我这里fork的吗？我是直接把统计代码放在了_layouts/index.html，你直接替换成你的就好了。

**Comment by stuhua** [comment]
谢了，我的可以用了。。。:smile: :smile: :smile:
